### ISSUE TITLE
Michael's TODO list

### ISSUE THREAD

**Issue by schickimiki** [githubteacher/basel-october-developers#4]
# My hometown is [Bottmingen](https://www.google.ch/maps/place/Bottmingen/@47.5210887,7.5567076,14z/data=!3m1!4b1!4m5!3m4!1s0x4791b87c51b672c9:0x3643c83ad83de63c!8m2!3d47.5233885!4d7.5723451)
- [x ] Create a branch for my hometown
- [x] Add my hometown file
- [x] Open a Pull Request
- [x] Add things to do

**Comment by schickimiki** [comment]
https://guides.github.com/introduction/flow/

**Comment by schickimiki** [comment]
Closing the issue, as we're done!
